declare namespace Express {
	/*
		NOTE: The naming-convention rule has been disabled for this line because
		Request is part of @types/express and can't be renamed to
		iRequest
	 */
	// eslint-disable-next-line @typescript-eslint/naming-convention
	export interface Request {
		/**
		 * Unique request ID generated by the middleware.
		 */
		uniqueRequestId: string;

		/*
			Please refer the below mentioned StackOverflow link to understand
			why we're using import() function instead of importing it normally
			at the top of the file:

			https://stackoverflow.com/a/51114250/6793156
		*/
		decodedAccessToken: import("@customTypes/appDataTypes/authTypes").iJWTPayload;
	}
}
