/**
 * Better Auth schema exports.
 *
 * These tables are used by better-auth for authentication and authorization.
 * All tables use UUID primary keys generated by PostgreSQL.
 */
export * from "./betterAuth.schema.js";
