import {httpStatusCodes} from "@/customTypes/NetworkTypes";
import {GenericNullable, NullableString} from "@/customTypes/CommonTypes";

interface iValidationErrorDetails {
	source: string;
	keys: Array<string | number>;
	message: string;
}

type ValidationErrorsType = Record<string, iValidationErrorDetails>;

interface iPaginationInfo {
	// Current page number.
	page: number;

	// Number of items per page.
	pageSize: number;

	// Total number of pages.
	totalPages: number;

	// Total number of items.
	totalItems: number;
}

type NullablePaginationInfo = iPaginationInfo | null;

interface iResponseMeta {
	// Unique request ID generated by the middleware.
	URID: NullableString;

	// Pagination information.
	paginationInfo: NullablePaginationInfo;
}

interface iServiceError {
	error: string;
	message: string;
	validationErrors?: ValidationErrorsType | null;
}

interface iServiceSuccess {
	message: string;
}

type NullableServiceError = iServiceError | null;
type NullableServiceSuccess = iServiceSuccess | null;

type ServiceErrorMapType = {
	[key in string]: iServiceError;
};

type ServiceSuccessMapType = {
	[key in string]: iServiceSuccess;
};

type MultiServiceErrorMapTypeObject = {
	[key in string]: ServiceErrorMapType;
};

type MultiServiceSuccessMapTypeObject = {
	[key in string]: ServiceSuccessMapType;
};

interface iGenericResponse<SuccessResultType> {
	error: GenericNullable<iServiceError>;
	meta: iResponseMeta;
	data: GenericNullable<SuccessResultType>;
}

interface iGenericThunkUnwrapException {
	httpStatusCode: httpStatusCodes;
	message: iGenericResponse<null>;
}

/**
 * Function create iServiceError type object with type checking
 * but without loosing the inferred types and auto-complete in IDE.
 *
 * See: https://stackoverflow.com/a/52157355/6793156
 *
 * @param arg
 * @returns frozenServiceError
 */
function asTypeIServiceError<T extends MultiServiceErrorMapTypeObject>(
	arg: T
): T {
	return Object.freeze<T>(arg);
}

/**
 * Function create iServiceSuccess type object with type checking
 * but without loosing the inferred types and auto-complete in IDE.
 *
 * See: https://stackoverflow.com/a/52157355/6793156
 *
 * @param arg
 * @returns frozenServiceSuccess
 */
function asTypeIServiceSuccess<T extends MultiServiceSuccessMapTypeObject>(
	arg: T
): T {
	return Object.freeze<T>(arg);
}

export {asTypeIServiceError, asTypeIServiceSuccess};

export type {
	MultiServiceErrorMapTypeObject,
	MultiServiceSuccessMapTypeObject,
	iResponseMeta,
	iServiceError,
	iServiceSuccess,
	NullableServiceError,
	NullableServiceSuccess,
	iGenericResponse,
	iValidationErrorDetails,
	ValidationErrorsType,
	NullablePaginationInfo,
	iGenericThunkUnwrapException,
};
