/**
 * HTTP Status Codes
 */
export enum httpStatusCodes {
	// 2xx Success
	SUCCESS_OK = 200,
	SUCCESS_CREATED = 201,
	SUCCESS_ACCEPTED = 202,
	SUCCESS_NO_CONTENT = 204,

	// 3xx Redirection
	REDIRECT_MOVED_PERMANENTLY = 301,
	REDIRECT_FOUND = 302,
	REDIRECT_NOT_MODIFIED = 304,

	// 4xx Client Errors
	CLIENT_ERROR_BAD_REQUEST = 400,
	CLIENT_ERROR_UNAUTHORIZED = 401,
	CLIENT_ERROR_FORBIDDEN = 403,
	CLIENT_ERROR_NOT_FOUND = 404,
	CLIENT_ERROR_METHOD_NOT_ALLOWED = 405,
	CLIENT_ERROR_CONFLICT = 409,
	CLIENT_ERROR_UNPROCESSABLE_ENTITY = 422,
	CLIENT_ERROR_TOO_MANY_REQUESTS = 429,

	// 5xx Server Errors
	SERVER_ERROR_INTERNAL_SERVER_ERROR = 500,
	SERVER_ERROR_NOT_IMPLEMENTED = 501,
	SERVER_ERROR_BAD_GATEWAY = 502,
	SERVER_ERROR_SERVICE_UNAVAILABLE = 503,
}
